pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'death-rewind-fabric-1.21'

def mineBackupDir = providers.gradleProperty('minebackupDir')
        .getOrElse('../../../Fabric/Fabric-1.21')

includeBuild(mineBackupDir) {
    name = 'minebackup-fabric-1.21'
    dependencySubstitution {
        substitute module('com.leafuke.minebackup:minebackup') using project(':')
    }
}
