pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'death-rewind-fabric-26.2'

def mineBackupDir = providers.gradleProperty('minebackupDir')
		.getOrElse('../../../Fabric/Fabric-26.2')

includeBuild(mineBackupDir) {
	name = 'minebackup-fabric-26.2'
	dependencySubstitution {
		substitute module('com.leafuke.minebackup:minebackup') using project(':')
	}
}
